_target_: src.models.MIWAE
_recursive_: false  

K: 5
latent_dim: 20
param_dim: 1
param_output_channel: ${mul:${data.dim},${model.param_dim}}
param_output_dim: ${mul:${prod:${data.shape}},${model.param_dim}} # For decoder output

likelihood:
  _target_: src.likelihoods.BernoulliLikelihood
  param_dim: ${model.param_dim}
  
# From EDDI paper
encoder:
  _target_: src.layers.PNPEncoder
  input_dim: ${data.dim}
  emb_dim: 20
  h_dim: 500
  hidden_dims: [500, 500, 200]
  latent_dim: ${model.latent_dim}
    
decoder:
  _target_: src.layers.MLP
  input_dim: ${model.latent_dim}
  hidden_dims: [200, 500, 500]
  output_dim: ${model.param_output_dim}
  activation: "relu"
  output_shape: [28,28]
