name: ebm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - wandb
      - lightning
      - hydra-core
      - einops
      - matplotlib
      - pandas
      - kaggle
      - scikit-learn
